services:
  qhana-ui:
    build: ./qhana-ui
    image: qhana-ui
    ports:
      - "4200:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  qhana-plugin-runner:
    build: ./qhana-plugin-runner
    image: qhana-plugin-runner
    depends_on:
      - redis
      - postgres
    ports:
      - "5005:8080"
    volumes:
      - instance:/app/instance
      - ./qhana-plugin-runner/plugins:/app/plugins
    environment:
      CONCURRENCY: 2
      BROKER_URL: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres:5432/default_db"
      URL_MAP: '{"(https?://)(localhost|host.docker.internal):9090": "\\1backend:9090"}'

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: default_db
  muse-db:
    build: ./qhana-plugin-runner/plugins/costume_loader_pkg/db_container
    image: "muse-db"
    profiles:
      - with_db

  worker:
    image: qhana-plugin-runner
    build: ./qhana-plugin-runner
    depends_on:
      - qhana-plugin-runner
    volumes:
      - instance:/app/instance
      - ./qhana-plugin-runner/plugins:/app/plugins
    environment:
      CONTAINER_MODE: worker
      CONCURRENCY: 2
      BROKER_URL: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres:5432/default_db"
      URL_MAP: '{"(https?://)(localhost|host.docker.internal):9090": "\\1backend:9090"}'
  backend:
    image: ghcr.io/ust-quantil/qhana-backend:main
    volumes:
      - experiments:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      QHANA_URL_MAPPING: '{"(?<=^|https?://)(localhost|host.docker.internal):5005": "qhana-plugin-runner:8080", "(?<=^|https?://)localhost(:[0-9]+)?": "host.docker.internal$$1"}'
    ports:
      - 9090:9090
        
  nisq-analyzer-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: nisq
      POSTGRES_USER: nisq
      POSTGRES_DB: nisq
    command: -p 5060
    ports:
      - "5060:5060"
  nisq-analyzer:
    image: planqk/nisq-analyzer:latest
    environment:
      POSTGRES_HOSTNAME: nisq-analyzer-db
      POSTGRES_PORT: 5060
      POSTGRES_USER: nisq
      POSTGRES_PASSWORD: nisq
      POSTGRES_DB: nisq

      # activate correct application properties
      SPRING_PROFILES_ACTIVE: docker

      TRANSLATOR_HOSTNAME: quantum-transpiler
      TRANSLATOR_PORT: 5012
      # Configuration of the SDK Connector Services
      QISKIT_HOSTNAME: qiskit-service
      QISKIT_PORT: 5013
      FOREST_HOSTNAME: forest-service
      FOREST_PORT: 5014
      PYTKET_HOSTNAME: pytket-service
      PYTKET_PORT: 5015
      # Configure Prioritization Service connection
      PRIORITIZATION_HOSTNAME: qhana-plugin-runner
      PRIORITIZATION_PORT: 8080
    ports:
      - '5010:5010'
    networks:
      - default

  nisq-analyzer-ui:
    build: ./nisq-analyzer-ui
    image: nisq-analyzer-ui
    environment:
      NISQ_ANALYZER_HOST_NAME: localhost
      NISQ_ANALYZER_PORT: 5010
    ports:
      - '4201:80'
    networks:
      - default

  qiskit-service:
    image: planqk/qiskit-service:latest
    command: sh /app/startup.sh
    ports:
      - "5013:5013"
    environment:
      - REDIS_URL=redis://nisq-analyzer-redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default

  qiskit-rq-worker:
    image: planqk/qiskit-service:latest
    command: rq worker --url redis://nisq-analyzer-redis:5040 qiskit-service_execute
    environment:
      - REDIS_URL=redis://nisq-analyzer-redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - nisq-analyzer-redis
    deploy:
      replicas: 2
  nisq-analyzer-redis:
    image: redis:6.2.2
    ports:
      - "5040:5040"
    command: --port 5040
    networks:
      - default

  gateway:
    image: planqk/gateway:latest
    environment:
      NISQ_ANALYZER_URI: http://localhost:5010
    ports:
      - '6473:6473'
    networks:
      - default

volumes:
  instance:
  experiments:
  exec_data:

networks:
  default:
    driver: bridge
      